spring.redis.reactive.host=rds.tahakara.dev
spring.redis.reactive.port=6379
spring.redis.reactive.password=14340801

spring.datasource.url=jdbc:postgresql://pgs.tahakara.dev:5432/test
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

auth.jwt.secret=YouWereTheChosenOne!ItWasSaidThatYouWouldDestroyTheSith,NotJoinThem!BringBalanceToTheForce,NotLeaveItInDarkness!.....YouWereMyBrother,Anakin.ILovedYou.
auth.jwt.issuer=labrotory.localhost:8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=taha.kara.37@gmail.com
spring.mail.password=rzaedzgqwisxbdjk
spring.mail.noreplysender=noreplylab@tahakara.dev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.domain=localhost:8080
api.protocol=http

# Change Front App Domain
app.domain=localhost:8080
app.support.mail=support@tahakara.dev
app.logo.url=https://dummyimage.com/100x50/000/fff