-- POSTGRESQL
USE HOSPITAL_LAB_DB;

CREATE TABLE IF NOT EXISTS "ADMINS" ( 
    ADMIN_ID BIGSERIAL PRIMARY KEY,
    
    ADMIN_HOSPITAL_ID VARCHAR(7) UNIQUE,
    ADMIN_IDENTIFICATION_NUMBER VARCHAR(11) NOT NULL UNIQUE,
    ADMIN_NAME VARCHAR(255) NOT NULL,
    ADMIN_SURNAME VARCHAR(255) NOT NULL,
    ADMIN_EMAIL VARCHAR(255) NOT NULL,
    ADMIN_PASSWORD VARCHAR(256) NOT NULL, -- Will be SHA-256 Hashed
    ADMIN_VERIFICATION_CODE VARCHAR(64),
    ADMIN_IS_VERIFIED BOOLEAN DEFAULT FALSE,

    ADMIN_UUID VARCHAR(36) DEFAULT (gen_random_uuid()) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);  

-- Index for search optimization
CREATE INDEX IF NOT EXISTS ADNIM_UUID_INDEX ON "ADMINS" (ADMIN_UUID);
CREATE INDEX IF NOT EXISTS ADMIN_IDENTIFICATION_NUMBER_INDEX ON "ADMINS" (ADMIN_IDENTIFICATION_NUMBER);
CREATE INDEX IF NOT EXISTS ADMIN_IS_VERIFIED_INDEX ON "ADMINS" (ADMIN_IS_VERIFIED);


--Stored Procedure
-- Insert User
```
CREATE OR REPLACE FUNCTION INSERET_NEW_ADMIN(
    IN P_ADMIN_HOSPITAL_ID VARCHAR(7),
    IN P_ADMIN_IDENTIFICATION_NUMBER VARCHAR(11),
    IN P_ADMIN_NAME VARCHAR(255),
    IN P_ADMIN_SURNAME VARCHAR(255),
    IN P_ADMIN_EMAIL VARCHAR(255),
    IN P_ADMIN_PASSWORD VARCHAR(256),
    OUT P_ADMIN_UUID UUID,
    OUT P_SUCCESS BOOLEAN
)
AS $$
DECLARE
    NEW_ADMIN_UUID UUID;
BEGIN
    -- CREATE NEW ADMIN
    BEGIN
        INSERT INTO "ADMIN" (
            ADMIN_HOSPITAL_ID,
            ADMIN_IDENTIFICATION_NUMBER,
            ADMIN_NAME, 
            ADMIN_SURNAME, 
            ADMIN_EMAIL, 
            ADMIN_PASSWORD
        ) VALUES (
            P_ADMIN_HOSPITAL_ID,
            P_ADMIN_IDENTIFICATION_NUMBER,
            P_ADMIN_NAME, 
            P_ADMIN_SURNAME, 
            P_ADMIN_EMAIL, 
            P_ADMIN_PASSWORD
        )
        RETURNING ADMIN_UUID INTO NEW_ADMIN_UUID;
        
        P_SUCCESS := TRUE;
    EXCEPTION WHEN others THEN
        P_SUCCESS := FALSE;
    END;

    P_ADMIN_UUID := NEW_ADMIN_UUID;
END;
$$ LANGUAGE plpgsql;

```

-- Insert User
-- INSERT INTO "ADMIN" (ADMIN_NAME,ADMIN_SURNAME,ADMIN_EMAIL,ADMIN_PASSWORD) VALUES ('TAHA','KARA','TAHA@TAHA.TAHA','A3456789JHGFD'); 


-- Select User
-- SELECT * FROM "ADMIN";
-- SELECT * FROM "ADMIN" WHERE ADMIN_ID = 1;



-- UPDATE 
-- -- -- UPDATE 
-- -- --     "ADMIN"
-- -- -- SET 
-- -- --     ADMIN_SURNAME = 'YENI_1M', 
-- -- --     UPDATED_AT = CURRENT_TIMESTAMP
-- -- -- WHERE 
-- -- --     ADMIN_ID = 1;

