-- POSTGRESQL
USE HOSPITAL_LAB_DB;

CREATE TABLE IF NOT EXISTS "LABORANTS" ( 
    LABORANT_ID BIGSERIAL PRIMARY KEY,
    
    LABORANT_HOSPITAL_ID VARCHAR(7) UNIQUE NOT NULL,
    LABORANT_IDENTIFICATION_NUMBER VARCHAR(11) NOT NULL UNIQUE,
    LABORANT_NAME VARCHAR(255) NOT NULL,
    LABORANT_SURNAME VARCHAR(255) NOT NULL,
    LABORANT_EMAIL VARCHAR(255) NOT NULL,
    LABORANT_PASSWORD VARCHAR(256) NOT NULL, -- Will be SHA-256 Hashed
    LABORANT_VERIFICATION_CODE VARCHAR(64),
    LABORANT_IS_VERIFIED BOOLEAN DEFAULT FALSE,
    LABORANT_IS_ACTIVE_WORK BOOLEAN DEFAULT FALSE,

    LABORANT_UUID VARCHAR(36) DEFAULT (gen_random_uuid()) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);  

-- Index
CREATE INDEX IF NOT EXISTS LABORANT_UUID_INDEX ON "LABORANTS" (LABORANT_UUID);
CREATE INDEX IF NOT EXISTS LABORANT_IDENTIFICATION_NUMBER_INDEX ON "LABORANTS" (LABORANT_IDENTIFICATION_NUMBER);
CREATE INDEX IF NOT EXISTS LABORANT_IS_VERIFIED_INDEX ON "LABORANTS" (LABORANT_IS_VERIFIED);

--Stored Procedure
-- Insert User
```
CREATE OR REPLACE FUNCTION INSERET_NEW_LABORANT(
    IN P_LABORANT_HOSPITAL_ID VARCHAR(7),
    IN P_LABORANT_IDENTIFICATION_NUMBER VARCHAR(11),
    IN P_LABORANT_NAME VARCHAR(255),
    IN P_LABORANT_SURNAME VARCHAR(255),
    IN P_LABORANT_EMAIL VARCHAR(255),
    IN P_LABORANT_PASSWORD VARCHAR(256),
    OUT P_LABORANT_UUID UUID,
    OUT P_SUCCESS BOOLEAN
)
AS $$
DECLARE
    NEW_LABORANT_UUID UUID;
BEGIN
    -- CREATE NEW LABORANT
    BEGIN
        INSERT INTO "LABORANT" (
            LABORANT_HOSPITAL_ID, -- HOSPITAL ID 7 DIGIT
            LABORANT_IDENTIFICATION_NUMBER,
            LABORANT_NAME, 
            LABORANT_SURNAME, 
            LABORANT_EMAIL, 
            LABORANT_PASSWORD
        ) VALUES (
            P_LABORANT_HOSPITAL_ID,
            P_LABORANT_IDENTIFICATION_NUMBER,
            P_LABORANT_NAME, 
            P_LABORANT_SURNAME, 
            P_LABORANT_EMAIL, 
            P_LABORANT_PASSWORD
        )
        RETURNING LABORANT_UUID INTO NEW_LABORANT_UUID;
        
        P_SUCCESS := TRUE;
    EXCEPTION WHEN others THEN
        P_SUCCESS := FALSE;
    END;

    P_LABORANT_UUID := NEW_LABORANT_UUID;
END;
$$ LANGUAGE plpgsql;

```

-- Insert User
-- INSERT INTO "LABORANT" (LABORANT_NAME,LABORANT_SURNAME,LABORANT_EMAIL,LABORANT_PASSWORD) VALUES ('TAHA','KARA','TAHA@TAHA.TAHA','A3456789JHGFD'); 


-- Select User
-- SELECT * FROM "LABORANT";
-- SELECT * FROM "LABORANT" WHERE LABORANT_ID = 1;



-- UPDATE 
-- -- -- UPDATE 
-- -- --     "LABORANT"
-- -- -- SET 
-- -- --     LABORANT_SURNAME = 'YENI_1M', 
-- -- --     UPDATED_AT = CURRENT_TIMESTAMP
-- -- -- WHERE 
-- -- --     LABORANT_ID = 1;

